'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { signOut } from 'next-auth/react';
import { Activity, ArrowDownToLine, ArrowUpRight, BarChart3, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Layers3, LayoutDashboard, LogOut, Mail, Pencil, Plus, RefreshCw, Search, ShieldCheck, Trash2, Users, X } from 'lucide-react';
const initials=name=>name.split(' ').map(x=>x[0]).slice(0,2).join('');
const date=value=>new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
const blank={name:'',email:'',role:'Member',status:'Active',team:'Engineering'};
export default function Dashboard({account}) {
  const [view,setView]=useState('Overview'),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [search,setSearch]=useState(''),[role,setRole]=useState('All roles'),[status,setStatus]=useState('All statuses'),[page,setPage]=useState(1),[range,setRange]=useState(90);
  const [editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[formError,setFormError]=useState('');
  const editDialog=useRef(null),deleteDialog=useRef(null),helpDialog=useRef(null);
  const admin=account.role==='Admin';
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/users',{cache:'no-store'});const result=await r.json();if(!r.ok)throw new Error(result.error);setData(result);}catch(e){setError(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(id);},[notice]);
  useEffect(()=>{setPage(1);},[search,role,status]);
  function openEdit(user) {setEditing(user||{...blank});setFormError('');editDialog.current.showModal();}
  function openDelete(user) {setDeleting(user);setFormError('');deleteDialog.current.showModal();}
  async function mutate(method,values) {
    setBusy(true);setFormError('');
    try {const r=await fetch('/api/users',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,revision:data.revision})});const next=await r.json();if(!r.ok){if(r.status===409)await load();throw new Error(next.error);}setData(next);editDialog.current.close();deleteDialog.current.close();setNotice(method==='DELETE'?'User removed.':method==='POST'?'User added.':'Changes saved.');setPage(1);}
    catch(e){setFormError(e.message);}finally{setBusy(false);}
  }
  const users=data?.users||[],events=data?.events||[];
  const active=users.filter(u=>u.status==='Active').length,invited=users.filter(u=>u.status==='Invited').length,admins=users.filter(u=>u.role==='Admin').length;
  const filtered=users.filter(u=>(role==='All roles'||u.role===role)&&(status==='All statuses'||u.status===status)&&`${u.name} ${u.email} ${u.team}`.toLowerCase().includes(search.toLowerCase()));
  const pages=Math.max(1,Math.ceil(filtered.length/8)),currentPage=Math.min(page,pages);
  const rows=(view==='Overview'?users.slice(0,5):filtered.slice((currentPage-1)*8,currentPage*8));
  const daily=Array.from({length:8},(_,i)=>{const end=Date.now()-((7-i)*range/8)*86400000;const start=end-(range/8)*86400000;return{label:new Date(end).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}),count:users.filter(u=>new Date(u.createdAt)>start&&new Date(u.createdAt)<=end).length};});
  const max=Math.max(1,...daily.map(x=>x.count));
  function exportCSV() {const safe=value=>'"'+String(value).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const csv=[['Name','Email','Role','Status','Team','Joined'],...filtered.map(u=>[u.name,u.email,u.role,u.status,u.team,u.createdAt])].map(row=>row.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='kavya-users.csv';a.click();URL.revokeObjectURL(url);setNotice('User directory exported.');}
  const nav=[['Overview',LayoutDashboard],['Users',Users],['Analytics',BarChart3],['Activity',Activity]];
  function Table(){return <div className="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Team</th><th>Joined</th>{admin&&<th className="action-heading">Actions</th>}</tr></thead><tbody>{rows.map(u=><tr key={u.id}><td><div className="person"><span className={'avatar tone-'+(u.name.charCodeAt(0)%4)}>{initials(u.name)}</span><div><strong>{u.name}</strong><small>{u.email}</small></div></div></td><td><span className="role">{u.role==='Admin'&&<ShieldCheck size={13}/>} {u.role}</span></td><td><span className={'badge '+u.status.toLowerCase()}><i/>{u.status}</span></td><td>{u.team}</td><td className="date">{date(u.createdAt)}</td>{admin&&<td><div className="row-actions"><button className="icon-button" title={'Edit '+u.name} aria-label={'Edit '+u.name} onClick={()=>openEdit(u)}><Pencil size={15}/></button><button className="icon-button danger-icon" title={'Delete '+u.name} aria-label={'Delete '+u.name} onClick={()=>openDelete(u)}><Trash2 size={15}/></button></div></td>}</tr>)}</tbody></table>{rows.length===0&&<div className="empty"><Search size={28}/><h3>No users found</h3><p>Try a different search or clear your filters.</p><button onClick={()=>{setSearch('');setRole('All roles');setStatus('All statuses');}}>Clear filters</button></div>}</div>;}
  function Growth(){return <section className="chart-panel"><div className="section-head"><div><h2>User growth</h2><p>New users added to the workspace</p></div><label className="sr-only" htmlFor="range">Analytics period</label><select id="range" value={range} onChange={e=>setRange(Number(e.target.value))}><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></div><div className="chart" role="img" aria-label={daily.map(d=>`${d.label}: ${d.count} new users`).join('; ')}>{daily.map((d,i)=><div className="bar-column" key={i}><div className="bar-track"><span className="bar-value">{d.count}</span><div className="bar" style={{height:`${d.count/max*135}px`}}/></div><small>{d.label}</small></div>)}</div><div className="chart-caption"><span className="legend-dot"/>New users <span className="muted">Based on stored join dates</span></div></section>;}
  function Distribution(){return <section className="chart-panel distribution"><div className="section-head"><div><h2>Workspace health</h2><p>Current user status</p></div><Activity size={19}/></div><div className="health-total"><strong>{users.length?Math.round(active/users.length*100):0}<span>%</span></strong><p>of users are active</p></div><div className="stacked" aria-label={`${active} active, ${invited} invited, ${users.length-active-invited} suspended`}>{['Active','Invited','Suspended'].map(s=><span key={s} className={s.toLowerCase()} style={{width:`${users.length?users.filter(u=>u.status===s).length/users.length*100:0}%`}}/>)}</div><div className="health-list">{['Active','Invited','Suspended'].map(s=><div key={s}><span><i className={'legend-dot '+s.toLowerCase()}/>{s}</span><strong>{users.filter(u=>u.status===s).length}</strong></div>)}</div></section>;}
  return <div className="shell"><aside className="sidebar"><a href="/" className="brand"><span className="logo"><Layers3 size={21}/></span>Kavya Labs<span className="brand-dot"/></a><div className="workspace"><span className="workspace-mark">K</span><div><strong>Kavya workspace</strong><small>Team administration</small></div></div><span className="nav-label">WORKSPACE</span><nav>{nav.map(([label,Icon])=><button key={label} className={view===label?'selected':''} onClick={()=>{setView(label);setError('');}}><Icon size={18}/>{label}{label==='Users'&&<span className="nav-count">{users.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="demo-tag"><span className="status-dot"/>Demo workspace<small>Fictional team data</small></div><button className="help-button" onClick={()=>helpDialog.current.showModal()}><CircleHelp size={18}/>Workspace guide</button><div className="account"><span className="account-avatar">{initials(account.name||'Demo User')}</span><div><strong>{account.name}</strong><small>{account.role} access</small></div><button title="Sign out" aria-label="Sign out" onClick={()=>signOut({callbackUrl:'/login'})}><LogOut size={16}/></button></div></div></aside><div className="main-wrap"><header className="topbar"><div>Workspace <span>/</span><strong>{view}</strong></div><div className="top-right"><span className="live-dot"/>All changes saved <span className="top-avatar">{initials(account.name||'Demo User')}</span></div></header><main className="content"><div className="page-head"><div><div className="eyebrow">KAVYA LABS / ADMIN</div><h1>{view==='Overview'?'Workspace overview':view==='Users'?'User directory':view==='Analytics'?'Workspace analytics':'Activity log'}<span className="heading-dot">.</span></h1><p>{view==='Overview'?"A clear view of your team and what's happening.":view==='Users'?'Manage people, permissions, and workspace access.':view==='Analytics'?'Understand how your workspace is growing.':'Every user change, in one place.'}</p></div><div className="page-actions"><button onClick={load} className="icon-button refresh" aria-label="Refresh workspace" title="Refresh workspace" disabled={loading}><RefreshCw size={17} className={loading?'spin':''}/></button>{view==='Users'&&<button onClick={exportCSV} disabled={!data}><ArrowDownToLine size={16}/>Export</button>}{admin&&(view==='Users'||view==='Overview')&&<button className="primary" disabled={!data} onClick={()=>openEdit()}><Plus size={17}/>Add user</button>}</div></div>
  {!admin&&<div className="read-only"><ShieldCheck size={17}/>Read-only access. User changes require an administrator.</div>}
  {error&&<div className="error banner" role="alert">{error}<button onClick={load}>Retry</button></div>}
  {loading&&!data?<div className="loading"><RefreshCw className="spin"/>Loading workspace...</div>:data&&<>
  {(view==='Overview'||view==='Analytics')&&<><div className="stats">{[['Total users',users.length,Users,'Across your workspace'],['Active users',active,Activity,'Currently enabled'],['Pending invites',invited,Mail,'Awaiting activation'],['Administrators',admins,ShieldCheck,'Workspace access managers']].map(([label,value,Icon,hint])=><section className="stat" key={label}><div><span>{label}</span><Icon size={18}/></div><strong>{value.toString().padStart(2,'0')}</strong><small>{hint}</small></section>)}</div><div className="chart-grid"><Growth/><Distribution/></div></>}
  {(view==='Overview'||view==='Users')&&<section className="users-panel"><div className="section-head"><div><h2>{view==='Overview'?'Team members':'All users'}<span className="count">{users.length}</span></h2><p>{view==='Overview'?'Your people, connected.':'Everyone with a place in your workspace.'}</p></div>{view==='Overview'&&<button className="text-button" onClick={()=>setView('Users')}>View all users<ArrowUpRight size={16}/></button>}</div>{view==='Users'&&<div className="filters"><div className="search-input"><Search size={17}/><input placeholder="Search name, email, or team..." aria-label="Search users" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={15}/></button>}</div><select aria-label="Filter by role" value={role} onChange={e=>setRole(e.target.value)}>{['All roles','Admin','Member','Viewer'].map(r=><option key={r}>{r}</option>)}</select><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}>{['All statuses','Active','Invited','Suspended'].map(s=><option key={s}>{s}</option>)}</select></div>}<Table/>{view==='Users'&&<div className="pagination"><span>{filtered.length?`${(currentPage-1)*8+1}-${Math.min(currentPage*8,filtered.length)}`:'0'} of {filtered.length} users</span><div><button aria-label="Previous page" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><span>Page {currentPage} of {pages}</span><button aria-label="Next page" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></div></div>}</section>}
  {view==='Analytics'&&<section className="users-panel"><div className="section-head"><div><h2>Team breakdown</h2><p>Membership by department</p></div></div><div className="team-breakdown">{['Engineering','Product','Design','Operations'].map(team=><div key={team}><span>{team}</span><div><span style={{width:`${users.length?users.filter(u=>u.team===team).length/users.length*100:0}%`}}/></div><strong>{users.filter(u=>u.team===team).length}</strong></div>)}</div></section>}
  {(view==='Activity'||view==='Overview')&&<section className="activity-panel"><div className="section-head"><div><h2>Recent activity</h2><p>{view==='Activity'?'Latest 100 saved actions':'The latest changes to your workspace'}</p></div>{view==='Overview'&&<button className="text-button" onClick={()=>setView('Activity')}>View activity<ArrowUpRight size={16}/></button>}</div>{events.slice(0,view==='Overview'?3:100).map(e=><div className="activity-row" key={e.id}><span className="activity-icon"><Clock3 size={16}/></span><div><strong>{e.action}</strong><p>{e.detail}</p><small>{e.actor}</small></div><time>{date(e.at)}<small>{new Date(e.at).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'})} UTC</small></time></div>)}</section>}
  </>}<footer className="page-footer"><span>Kavya Labs <span className="muted">/ Team workspace</span></span><span>Week 03 <span className="footer-dot"/> Admin dashboard</span></footer></main></div>
  {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
  <dialog ref={editDialog} onCancel={e=>{if(busy)e.preventDefault();}}><div className="modal-head"><div><span className="eyebrow">USER MANAGEMENT</span><h2>{editing?.id?'Edit user':'Add a team member'}</h2></div><button className="icon-button" aria-label="Close user form" disabled={busy} onClick={()=>editDialog.current.close()}><X size={20}/></button></div>{editing&&<form onSubmit={e=>{e.preventDefault();mutate(editing.id?'PATCH':'POST',editing);}}><label>Full name<input autoFocus required minLength={2} maxLength={60} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Email address<input required type="email" maxLength={120} value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/></label><div className="form-grid"><label>Role<select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}>{['Admin','Member','Viewer'].map(v=><option key={v}>{v}</option>)}</select></label><label>Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}>{['Active','Invited','Suspended'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Team<select value={editing.team} onChange={e=>setEditing({...editing,team:e.target.value})}>{['Engineering','Product','Design','Operations'].map(v=><option key={v}>{v}</option>)}</select></label><small className="muted">Directory record only. No invitation email is sent.</small>{formError&&<p className="error" role="alert">{formError}</p>}<div className="modal-actions"><button type="button" disabled={busy} onClick={()=>editDialog.current.close()}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving...':editing.id?'Save changes':'Add user'}</button></div></form>}</dialog>
  <dialog ref={deleteDialog} onCancel={e=>{if(busy)e.preventDefault();}}><div className="modal-head"><h2>Remove {deleting?.name}?</h2><button className="icon-button" disabled={busy} aria-label="Close delete confirmation" onClick={()=>deleteDialog.current.close()}><X size={20}/></button></div><p className="muted">This removes the user from the directory. This action cannot be undone.</p>{formError&&<p className="error" role="alert">{formError}</p>}<div className="modal-actions"><button disabled={busy} onClick={()=>deleteDialog.current.close()}>Cancel</button><button className="destructive" disabled={busy} onClick={()=>mutate('DELETE',{id:deleting.id})}>{busy?'Removing...':'Remove user'}</button></div></dialog>
  <dialog ref={helpDialog}><div className="modal-head"><h2>About this workspace</h2><button className="icon-button" aria-label="Close guide" onClick={()=>helpDialog.current.close()}><X size={20}/></button></div><p>This Week 3 demo includes a user directory, analytics, and a saved activity log.</p><p>Admin accounts can add, edit, and remove directory records. Viewer accounts can browse and export. Directory roles describe team membership; login access is managed separately.</p><p>All data is fictional. Changes are shared between demo visitors and persist on the server. Analytics reflect the saved directory, not website traffic.</p></dialog>
  </div>;
}
